language: python
sudo: false
python:
    - 2.7

before_install:
  - sudo apt-get install --yes libsasl2-dev python-dev libldap2-dev libssl-dev libgtk-3-dev

before_script:
  - export ROBOT_SELENIUM2LIBRARY_RUN_ON_FAILURE="Capture Page Screenshot"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v


install:
    - pip install setuptools zc.buildout
    - pip install coveralls coverage requests nose-htmloutput nose
    - buildout bootstrap
    - buildout -N

# safelist
branches:
  only:
  - master

script:
    - coverage run bin/test -t genweb6.organs  --layer=\!Robot

after_success:
    - coverage combine
    - coveralls

cache:
  pip: true
  directories:
    - eggs/
    - $HOME/buildout-cache

addons:
  # XXX: use an older Firefox ESR as we are stuck with selenium = 2.53.5
  #      https://github.com/SeleniumHQ/selenium/issues/2739#issuecomment-249482533
  firefox: 45.8.0esr

notifications:
  email:
    recipients:
      - plone.team@upcnet.es
    on_success: change
    on_failure: change


# before_install:
#     - mkdir -p $HOME/buildout-cache/{downloads,eggs,extends}
#     - mkdir $HOME/.buildout
#     - echo "[buildout]" > $HOME/.buildout/default.cfg
#     - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
#     - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
#     - echo "extends-cache = $HOME/buildout-cache/extends" >> $HOME/.buildout/default.cfg
#     - echo "abi-tag-eggs = true" >> $HOME/.buildout/default.cfg


# before_script:
#   - export DISPLAY=:99.0
#   - export VERBOSE=true
#   - sh -e /etc/init.d/xvfb start

# after_script:
#   - sh -e /etc/init.d/xvfb stop
